POST http://localhost:3030/annonce
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI4OWM5NDMyMjE2OWQ5ZTkyYjA3NWEiLCJpYXQiOjE2Mzk0OTA0OTV9.mhKXEyeQc1EldWTIMF2XzE9ePzPXbdOoz80AxHD1od8

{
    "nom": "test23",
    "prix": 1200.22,
    "description": "nawak",
    "photo": "http:images.unsplash.com/photo-1636211992838-251a43d72ad2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    "categorie": "sport",
    "quantity": 2
}

### 

GET http://localhost:3030/annonce

### 

GET http://localhost:3030/annonce/61bb45fc9e91d9c98254c015

### 

DELETE http://localhost:3030/annonce/61bb0682b5a5f5632c22afe7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI5YmVkMDM5Y2FhMThhMWQ0NGI1ZWUiLCJpYXQiOjE2Mzk2NDE5MjV9.CrxKe50UK0PkRxRyVH8lmMshc96DWCJcKoIkh1-BeI4

####

PUT http://localhost:3030/annonce/61b768da82db40b038c80dd1
Content-Type: application/json

{
    "nom": "test",
    "prix": 1200.22,
    "description": "Basket",
    "photo": "http:images.unsplash.com/photo-1636211992838-251a43d72ad2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    "categorie": "sport",
    "quantity": 2
}

####

POST http://localhost:3030/signup
Content-Type: application/json

{
    "nom": "l'haricot",
    "prenom": "toto",
    "age": 520,
    "email": "t8ezer8yerr799@op.gh",
    "password": "12134",
    "photoProfile": "",
    "annonces": [],
    "panier": []
}

####

POST http://localhost:3030/login
Content-Type: application/json

{
    "email":"toto@toto",
    "password":"1234"
}

####

GET http://localhost:3030/user/annonces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI5YmVkMDM5Y2FhMThhMWQ0NGI1ZWUiLCJpYXQiOjE2Mzk2NjQ0ODB9.TGAsqSuyjxAlKQcxHvhoT_43cAa_l2qlnQTYRrp5GWk
